// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package peer_protocol

import "strconv"

const (
	_MessageType_name_0 = "ChokeUnchokeInterestedNotInterestedHaveBitfieldRequestPieceCancelPort"
	_MessageType_name_1 = "Suggest"
)

var (
	_MessageType_index_0 = [...]uint8{0, 5, 12, 22, 35, 39, 47, 54, 59, 65, 69}
)

func (i MessageType) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _MessageType_name_0[_MessageType_index_0[i]:_MessageType_index_0[i+1]]
	case i == 23:
		return _MessageType_name_1
	default:
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
